name: marina_hotel_mobile
description: "Marina Hotel - Complete Hotel Management System (RTL, Offline-First, Arabic)"
publish_to: 'none'
version: 1.1.0+3

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  drift: ^2.20.0
  drift_sqflite: ^2.0.1
  sqlite3_flutter_libs: ^0.5.24
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.0
  flutter_secure_storage: ^9.2.2
  fl_chart: ^0.69.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  pdf: ^3.11.1
  printing: ^5.13.2
  path_provider: ^2.1.4
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^2.5.7
  drift_dev: ^2.20.0

flutter:
  uses-material-design: true
