name: Kotlin Marina Android CI

on:
  push:
    paths:
      - 'kotlin-marina/**'
  pull_request:
    paths:
      - 'kotlin-marina/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Gradle cache
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: kotlin-marina

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: kotlin-marina

      - name: Assemble Debug
        run: ./gradlew --no-daemon assembleDebug
        working-directory: kotlin-marina

      - name: Run Lint
        run: ./gradlew --no-daemon lint
        working-directory: kotlin-marina

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-marina-app-debug-apk
          path: kotlin-marina/app/build/outputs/apk/debug/*.apk

      - name: Upload Lint Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-marina-lint-reports
          path: |
            kotlin-marina/app/build/reports/**
            kotlin-marina/app/build/outputs/lint-results*.*
