name: Build Kotlin Marina (APK)

on:
  workflow_dispatch:
    inputs:
      variant:
        description: 'Build variant'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release
  push:
    branches:
      - main
      - ci-*
    paths:
      - 'android_app/**'
      - '.github/workflows/build-kotlin-marina.yml'
  pull_request:
    branches:
      - main

jobs:
  build_apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kotlin-marina 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Build Debug APK (always tested)
        run: ./gradlew assembleDebug --scan

      - name: Build Release APK (if requested)
        if: github.event_name == 'workflow_dispatch' && inputs.variant == 'release'
        run: ./gradlew assembleRelease --scan

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: marina-hotel-${{ (inputs.variant || 'debug') }}-apk
          path: |
            kotlin-marina/app/build/outputs/apk/${{ (inputs.variant || 'debug') }}/*.apk
          retention-days: 14
