name: Kotlin Marina Android CI

on:
  push:
    paths:
      - 'kotlin-marina/**'
  pull_request:
    paths:
      - 'kotlin-marina/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME: /usr/local/lib/android/sdk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Prepare Android SDK
        working-directory: kotlin-marina
        run: echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties

      # هذا هو السطر 18 تقريباً. تم التأكد من صحة المسافة البادئة.
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: kotlin-marina

      - name: Assemble Debug
        run: ./gradlew --no-daemon assembleDebug
        working-directory: kotlin-marina

      - name: Run Lint
        run: ./gradlew --no-daemon lint
        working-directory: kotlin-marina

      - name: Upload APK
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-marina-app-debug-apk
          path: kotlin-marina/app/build/outputs/apk/debug/*.apk
          retention-days: 1

      - name: Upload Lint Reports
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-marina-lint-reports
          path: |
            kotlin-marina/app/build/reports/**
            kotlin-marina/app/build/outputs/lint-results*.*
          retention-days: 1
