name: Build_kotlin-marina
 
on:
  push:
    paths:
      - 'kotlin-marina/**'
  pull_request:
    paths:
      - 'kotlin-marina/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('kotlin-marina/**/gradle.properties', 'kotlin-marina/**/build.gradle*', 'kotlin-marina/**/settings.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew
        working-directory: kotlin-marina

      - name: Build debug APK
        run: ./gradlew assembleDebug
        working-directory: kotlin-marina

      - name: Run Android lint
        run: ./gradlew lint
        working-directory: kotlin-marina

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-marina-debug-apk
          path: kotlin-marina/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
