name: Cleanup Failed Runs

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  cleanup_failed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install gh -y

      - name: Delete failed workflow runs and artifacts
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          echo "Fetching failed workflow runs..."
          runs=$(gh run list -R $REPO --limit 200 --json databaseId,status,conclusion,headBranch --jq '.[] | select(.conclusion=="failure") | .databaseId')

          for run_id in $runs; do
            branch=$(gh run view $run_id -R $REPO --json headBranch --jq '.headBranch')
            echo "Deleting failed run ID: $run_id from branch: $branch"

            artifacts=$(gh api repos/$REPO/actions/runs/$run_id/artifacts --jq '.artifacts[].id')
            for artifact_id in $artifacts; do
              echo "Deleting artifact ID: $artifact_id"
              gh api --method DELETE repos/$REPO/actions/artifacts/$artifact_id >/dev/null
            done

            gh api --method DELETE repos/$REPO/actions/runs/$run_id >/dev/null
          done

          echo "تم حذف كل الـ workflow runs الفاشلة وكل الـ artifacts الخاصة بها."
