name: Clean Old Artifacts

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install gh -y

      - name: Delete old artifacts
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          echo "Fetching all completed workflow runs..."
          runs=$(gh run list -R $REPO --limit 100 --json databaseId,status --jq '.[] | select(.status=="completed") | .databaseId')

          for run_id in $runs; do
            echo "Processing run ID: $run_id"
            artifacts=$(gh run-artifact list $run_id -R $REPO --json id,name --jq '.[] | .id')
            for artifact_id in $artifacts; do
              echo "Deleting artifact ID: $artifact_id"
              gh run-artifact delete $artifact_id -R $REPO -y
            done
          done

          echo "تم حذف كل الـ artifacts القديمة."
