name: Build Marina Hotel APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Create necessary directories
      run: |
        mkdir -p android_app/src/main/res/font
        mkdir -p android_app/src/main/res/drawable
        mkdir -p android_app/src/main/res/layout

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build APK with retry
      run: |
        cd android_app
        # محاولة البناء مع إعادة المحاولة التلقائية
        for i in {1..3}; do
          if ./gradlew clean assembleDebug --no-daemon --console=plain; then
            echo "Build successful on attempt $i"
            exit 0
          else
            echo "Build failed on attempt $i, retrying..."
            sleep 10
          fi
        done
        echo "Build failed after 3 attempts"
        exit 1

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: marina-hotel-app
        path: android_app/app/build/outputs/apk/debug/app-debug.apk
