name: Test Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true
          
      - name: Flutter Doctor
        run: flutter doctor -v
        
      - name: Check Project Structure
        run: |
          echo "=== PROJECT STRUCTURE ==="
          ls -la
          echo "=== MOBILE DIRECTORY ==="
          ls -la mobile/
          echo "=== ANDROID DIRECTORY ==="
          ls -la mobile/android/
          
      - name: Get Dependencies
        working-directory: mobile
        run: |
          echo "Getting Flutter dependencies..."
          flutter pub get
          
      - name: Build APK
        working-directory: mobile
        env:
          BASE_API_URL: 'http://hotelmarina.com/MARINA_HOTEL_PORTABLE/api/v1'
        run: |
          echo "Building debug APK..."
          flutter build apk --debug --dart-define=BASE_API_URL=$BASE_API_URL